"""
Fill a DEMONSTRATION data directory, so the gates can be seen opening.

    python tools/seed_demo.py
    streamlit run console/app.py -- --data demo

WHY THIS EXISTS
---------------
Half of what this platform does is refuse. The yield is locked until thirty
weighed harvests exist, the nitrogen is locked until leaf samples exist, and no
disease is named until somebody walks out and looks. Those refusals are the
point.

But a demonstration in which every gate is shut shows only half the design. A
reader sees "not available" nine times and cannot tell whether the tool is
careful or simply unfinished - and the thing that makes it careful is precisely
what happens WHEN the gate opens: the figure arrives with its error, its sample
count, and the name of the person who measured it.

So this writes a synthetic ground-truth set into its own directory, and every
row of it is stamped.

WHAT KEEPS THIS FROM BECOMING A LIE
-----------------------------------
1. It writes to `demo/`, never to the working directory. The real stores stay
   empty, because they should be: nobody has measured anything yet.
2. Every record carries observer "DEMONSTRATION" and a note saying it is
   synthetic. The stamp is in the DATA, so it survives being copied out of the
   directory that explains it.
3. It refuses to run against a directory that already holds real records. A
   tool that can overwrite a season of somebody's scouting with invented rows
   is a tool that eventually will.
4. The numbers are generated from a declared relationship with declared noise,
   printed on creation. Nobody should ever mistake the fitted model for a
   finding, and the fit is meant to be good - a demonstration of a working
   calibration, not a claim about sorghum.

WHAT IT DOES NOT DO
-------------------
It does not touch the satellite side. Those measurements are real, from Earth
Engine, and no part of the demonstration invents one.
"""

from __future__ import annotations

import argparse
import os
import random
import sys
from datetime import date, timedelta

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import agronomy as ag                                    # noqa: E402
import farm_records as fr                                # noqa: E402
import nutrition_climate_ground as ncg                   # noqa: E402


STAMP = "DEMONSTRATION"
NOTE = ("SYNTHETIC demonstration record. Generated by tools/seed_demo.py. "
        "Nobody measured this.")

# The relationship the synthetic harvests are drawn from, and the noise around
# it. Printed on creation so the fitted model can never be mistaken for a
# discovery: it is this line, recovered.
YIELD_SLOPE = 8.5          # t/ha per unit NDVI
YIELD_INTERCEPT = -1.1     # t/ha
YIELD_NOISE = 0.18         # t/ha, one standard deviation


def _demo_report(path: str = None) -> dict:
    """The real satellite report the synthetic walks are scored against.

    Real measurements on one side, invented observations on the other - which
    is exactly the arrangement the agreement rate is built to describe.
    """
    import json
    path = path or os.path.join(os.path.dirname(__file__), "..", "docs",
                                "farm_report_demo.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _already_real(path: str) -> list:
    """Rows in an existing store that this script did not write.

    A tool that can overwrite a season of somebody's scouting with invented
    rows is a tool that eventually will.
    """
    import sqlite3
    found = []
    for name, table, col in (("observations.db", "observations", "observer"),
                             ("farm_records.db", "operations", "reported_by")):
        p = os.path.join(path, name)
        if not os.path.exists(p):
            continue
        try:
            conn = sqlite3.connect(f"file:{p}?mode=ro", uri=True)
            n = conn.execute(
                f"SELECT COUNT(*) FROM {table} "
                f"WHERE {col} IS NULL OR {col} != ?", (STAMP,)).fetchone()[0]
            conn.close()
            if n:
                found.append(f"{name}: {n} rows not written by this script")
        except sqlite3.Error:
            pass
    return found


def seed(path: str = "demo", fields=("Field 1", "Field 2", "Field 3",
                                     "Field 4"), seed_value: int = 7,
         report_path: str = None) -> dict:
    rng = random.Random(seed_value)
    os.makedirs(path, exist_ok=True)
    out = {"path": os.path.abspath(path)}

    # ---------------------------------------------------------- scouting
    # Two named findings and two clean walks. The clean walks matter as much:
    # they are what makes the agreement rate a rate rather than a count of
    # problems.
    store = ncg.ObservationStore(os.path.join(path, "observations.db"))
    try:
        rows = [
            ("Field 2", "sorghum_anthracnose", "wilting", "2022-09-12"),
            ("Field 1", "striga", "patchy", "2022-08-28"),
            ("Field 3", "", "healthy", "2022-09-14"),
            ("Field 4", "", "healthy", "2022-09-14"),
        ]
        # SCORED against the real satellite report, exactly as the scouting
        # form scores a record at save time. Without this the agreement rate -
        # the only figure that measures this platform's accuracy rather than
        # claiming it - stays at zero even in the demonstration, and the one
        # thing worth showing is the thing that does not appear.
        report = _demo_report(report_path)
        scored = 0
        for i, (fid, problem, canopy, when) in enumerate(rows):
            obs = ncg.GroundObservation(
                obs_id=f"demo{i}", field_id=fid, observed_at=when,
                lat=14.42 + 0.01 * i, lon=33.10 + 0.01 * i, photo_path="",
                source="phone", observer=STAMP, crop="sorghum",
                canopy_condition=canopy, problem=problem, notes=NOTE)
            sat = {}
            if report:
                v = ncg.score_observation(obs, report)
                obs.satellite_agreement = v["verdict"]
                sat = v["satellite"]
                scored += v["verdict"] != "UNCLEAR"
            store.add(obs, satellite=sat)
        out["scouting"] = len(rows)
        out["scored"] = scored
        out["agreement"] = store.agreement_summary()
    finally:
        store.close()

    # ------------------------------------------------- yield calibration
    # Thirty weighed harvests, the number the gate actually asks for.
    yc = ag.YieldCalibrationStore(os.path.join(path, "yield_calibration.db"))
    for i in range(30):
        ndvi = 0.22 + 0.011 * i
        t_ha = max(0.2, YIELD_SLOPE * ndvi + YIELD_INTERCEPT
                   + rng.gauss(0, YIELD_NOISE))
        yc.add_point("sorghum", harvested_kg=t_ha * 1000.0, area_ha=1.0,
                     ndvi=ndvi, field_id=f"{STAMP} plot {i + 1}", season=2022)
    fit = yc.fit("sorghum")
    out["yield_points"] = 30
    out["yield_fit"] = {k: fit.get(k) for k in
                        ("fitted", "slope", "intercept", "r2",
                         "rmse_fraction", "n_points")}

    # ------------------------------------------------------- operations
    ops = fr.RecordStore(os.path.join(path, "farm_records.db"))
    try:
        n = 0
        base = date(2022, 7, 15)
        for f in fields:
            # The store validates the operation name against its own list and
            # refuses anything else, which is why these are its spellings and
            # not mine.
            for k, (kind, cost) in enumerate((("land_preparation", 4200.0),
                                              ("planting", 1800.0),
                                              ("fertiliser", 6500.0),
                                              ("weeding", 2400.0),
                                              ("irrigation", 3100.0))):
                ops.add_operation(fr.Operation(
                    field_id=f, date=(base + timedelta(days=20 * k)).isoformat(),
                    operation=kind, cost=cost * (0.85 + 0.3 * rng.random()),
                    currency="SDG", reported_by=STAMP, note=NOTE))
                n += 1
        out["operations"] = n
    finally:
        ops.close()

    return out


def main():
    p = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    p.add_argument("--path", default="demo")
    p.add_argument("--force", action="store_true",
                   help="write even if the directory holds records this "
                        "script did not create")
    a = p.parse_args()

    real = _already_real(a.path)
    if real and not a.force:
        print("REFUSING: this directory holds records that were not written "
              "by this script.")
        for r in real:
            print("  " + r)
        print("Invented rows must never be mixed into somebody's real "
              "measurements. Point --path somewhere else, or pass --force if "
              "you are certain.")
        return 1

    out = seed(a.path)
    print("=" * 72)
    print("SYNTHETIC DEMONSTRATION DATA - nobody measured any of this")
    print("=" * 72)
    print(f"  written to      : {out['path']}")
    print(f"  scouting records: {out['scouting']}  "
          "(2 named findings, 2 clean walks)")
    ag_sum = out.get("agreement") or {}
    if ag_sum.get("available"):
        print(f"  satellite agreed : "
              f"{round(100 * ag_sum['agreement_rate'])}% of "
              f"{ag_sum['total']} clear comparisons"
              + (f", {ag_sum['unclear']} unclear and excluded"
                 if ag_sum.get("unclear") else ""))
    else:
        print(f"  satellite agreed : not scored "
              f"({ag_sum.get('reason', 'no report to compare against')})")
    print(f"  weighed harvests: {out['yield_points']}  "
          "(the number the yield gate asks for)")
    print(f"  operations      : {out['operations']}")
    print()
    print("  the harvests were drawn from a DECLARED line, with noise:")
    print(f"    yield t/ha = {YIELD_SLOPE} * NDVI {YIELD_INTERCEPT:+} "
          f"+ N(0, {YIELD_NOISE})")
    f = out["yield_fit"]
    print(f"  and the fit recovers it: slope {f.get('slope')}, "
          f"intercept {f.get('intercept')}, r2 {f.get('r2')}")
    print("  That is the point. The model is this line, found again - not a "
          "finding about sorghum.")
    print()
    print("  Every row carries observer/reported_by = DEMONSTRATION and a note")
    print("  saying it is synthetic, so the stamp survives being copied out of")
    print("  the directory that explains it.")
    print()
    print("  Now:  streamlit run console/app.py -- --data " + a.path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
